export default {
	'arrow.uturn.left': '􀄼',
	'arrow.uturn.right': '􀄽',
	'bold': '􀅓',
	'italic': '􀅔',
	'decrease.indent': '􀋶',
	'increase.indent': '􀋵',
	'link': '􀉣',
	'list.dash': '􀋱',
	'list.bullet': '􀋲',
	'list.number': '􀋴',
	'strikethrough': '􀅖',
	'underline': '􀅕',
	'xmark': '􀆄',
};
